#! /bin/sh

ECHO
ECHO CLEANING...
ECHO

make clean

ECHO
ECHO CONFIGURING...
ECHO

./configure CC='clang -c -fPIC'

ECHO
ECHO MAKING OBJECTS...
ECHO

make

ECHO
ECHO BUILDING SHARED LIBRARY...
ECHO

cd src

clang -lusb-1.0 -g -Wall -O2 -arch x86_64 -arch arm64 -dynamiclib -undefined dynamic_lookup -o libdfuprog-0.9.dylib main.o arguments.o atmel.o commands.o dfu.o intel_hex.o stm32.o util.o

ECHO
ECHO Build complete!!
ECHO
